name: Build
on:
  push:
    branches:
      - '*'

jobs:
  test:
    name: ğŸ¤ Test
    runs-on: ubuntu-latest
    steps:
    - name: ğŸ›‘ Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: â¬‡ï¸ Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        fetch-depth: 5
    - name: ğŸ¤ Test Dashboard Frontend
      run: make test-dashboard-frontend
    - name: ğŸ¤ Test
      run: |
        make test
    - name: ğŸ˜ Test with Postgres store
      run: |
        make test-with-postgres

  cli:
    name: ğŸ—ï¸ Build CLI
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: â¬‡ï¸ Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        fetch-depth: 5

    - name: ğŸ—ï¸ Build chart configure frontend
      run: make build-cli-frontend
    - name: ğŸ—ï¸ Build stack frontend
      run: make build-stack-frontend
    - name: ğŸ—ï¸ Build CLI
      run: make build-cli
      env:
        VERSION: "ci-build"

  gimletd:
    name: ğŸ—ï¸ Build GimletD
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: â¬‡ï¸ Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        fetch-depth: 5
    - name: ğŸ—ï¸ Build GimletD
      run: make build-gimletd
      env:
        VERSION: "ci-build"

  agent:
    name: ğŸ—ï¸ Build Gimlet Agent
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: â¬‡ï¸ Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        fetch-depth: 5
    - name: ğŸ—ï¸ Build Gimlet Agent
      run: make build-agent
      env:
        VERSION: "ci-build"

  dashboard:
    name: ğŸ—ï¸ Build Gimlet Dashboard
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: â¬‡ï¸ Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        fetch-depth: 5
    - name: ğŸ—ï¸ Build Gimlet Dashboard
      run: make build-dashboard
      env:
        VERSION: "ci-build"

  dashboard-frontend:
    name: ğŸ—ï¸ Build Gimlet Dashboard Frontend
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: â¬‡ï¸ Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        fetch-depth: 5
    - name: ğŸ—ï¸ Build dashboard frontend
      run: make build-dashboard-frontend
